version: "3.9"
services:
  team-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql:5432/playerdb"
  postgresql:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRESS_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "playerdb"